/* ============================================================
   성경 세계사 연대표 — Data (ES module)
   2026. 06. 10. Update — 엑셀 연대표 정리 최종 (20110803) 기반으로 전면 갱신
   ============================================================ */

export const LANES = [
  { id: 'world',    label: '세계 역사',  watermark: 'WORLD HISTORY',     theme: 'light' },
  { id: 'church',   label: '교회 역사',  watermark: 'CHURCH HISTORY',    theme: 'dark', skew: true },
  { id: 'jewish',   label: '유대 역사',  watermark: 'JEWISH HISTORY',    theme: 'light' },
  { id: 'biblical', label: '성경 연대',  watermark: 'BIBLICAL TIMELINE', theme: 'dark', skew: true },
];

export const EVENTS_INITIAL = [
// ============ 2026. 06. 10. Update ============
  { id: 'ev001', lane:'biblical', type:'spot', start:-4200, title:'천지창조',
    y: 10, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 1:1]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev002', lane:'biblical', type:'spot', start:-4200, title:'아담과 하와',
    y: 46, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 5:3]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev003', lane:'biblical', type:'span', start:-2616, end:-2016, title:'셈',
    y: 71, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 11:10~11]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev004', lane:'biblical', type:'span', start:-2516, end:-2078, title:'아르박삿',
    y: 19, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 11:12~13]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev005', lane:'biblical', type:'span', start:-2481, end:-2048, title:'셀라',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 11:14~15]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev006', lane:'biblical', type:'span', start:-2451, end:-1987, title:'에벨',
    y: 37, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 11:16~17]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev007', lane:'biblical', type:'spot', start:-2400, title:'노아의 홍수',
    y: 49, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 7장]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev008', lane:'biblical', type:'spot', start:-2500, title:'바벨탑 건설과 흩어짐',
    y: 25, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 11:1~9]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev009', lane:'biblical', type:'span', start:-2166, end:-1991, title:'아브라함',
    y: 59, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 11:26, 25:7~8]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev010', lane:'biblical', type:'spot', start:-2091, title:'아브람이 하란을 떠남',
    y: 48, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 12:4]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev011', lane:'biblical', type:'span', start:-2066, end:-1886, title:'이삭',
    y: 17, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 21:3, 35:28~29]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev012', lane:'biblical', type:'spot', start:-2029, title:'사라의 장지로 막벨라밭 구입',
    y: 25, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 23장]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev013', lane:'biblical', type:'span', start:-2006, end:-1859, title:'야곱',
    y: 35, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 25:26, 49:33]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev014', lane:'biblical', type:'span', start:-1915, end:-1805, title:'요셉',
    y: 37, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 30:22~24, 50:22~26]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev015', lane:'biblical', type:'spot', start:-1898, title:'요셉, 이집트에 노예로',
    y: 79, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 37:28]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev016', lane:'biblical', type:'spot', start:-1885, title:'이집트 총리 대신이 됨',
    y: 18, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 41:26]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev017', lane:'biblical', type:'spot', start:-1876, title:'야곱 가족이 이집트로 이주',
    y: 25, heightPx: 30, z: 1, labelAlign:'right',
    description: '[창 46:1~7]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev018', lane:'biblical', type:'spot', start:-1876, title:'이집트에 거주한 기간 430년',
    y: 59, heightPx: 30, z: 1, labelAlign:'right',
    description: '[출 12:40~41]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev019', lane:'biblical', type:'span', start:-1526, end:-1406, title:'모세',
    y: 72, heightPx: 30, z: 1, labelAlign:'right',
    description: '[출 2:2, 신 34:5]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev020', lane:'biblical', type:'spot', start:-1486, title:'모세, 미디안으로 도피',
    y: 66, heightPx: 30, z: 1, labelAlign:'right',
    description: '[출 2:15]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev021', lane:'biblical', type:'spot', start:-1446, title:'이집트로 돌아옴',
    y: 36, heightPx: 30, z: 1, labelAlign:'right',
    description: '[출 4:27]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev022', lane:'biblical', type:'spot', start:-1446, title:'출애굽',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '[출 12:41]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev023', lane:'biblical', type:'spot', start:-1446, title:'출애굽 후 성전을 짓기까지',
    y: 14, heightPx: 30, z: 1, labelAlign:'right',
    description: '[왕상 6:1, 8:14~20]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev024', lane:'biblical', type:'span', start:-1446, end:-1406, title:'이스라엘 민족의 광야생활',
    y: 44, heightPx: 30, z: 1, labelAlign:'right',
    description: '[출~신]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev025', lane:'biblical', type:'spot', start:-1406, title:'여호수아 정복기',
    y: 29, heightPx: 30, z: 1, labelAlign:'right',
    description: '[수 1:1~2]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev026', lane:'biblical', type:'spot', start:-1406, title:'이스라엘 민족, 가나안 입성',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '[수 3:14~17]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev027', lane:'biblical', type:'span', start:-1400, end:-1100, title:'사사 시대',
    y: 48, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev028', lane:'biblical', type:'spot', start:-1050, title:'사울 즉위',
    y: 18, heightPx: 30, z: 1, labelAlign:'right',
    description: '[삼상 10:17~27]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev029', lane:'biblical', type:'spot', start:-1010, title:'다윗 즉위',
    y: 66, heightPx: 30, z: 1, labelAlign:'right',
    description: '[삼하 2:1~7, 5:1~5]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev030', lane:'biblical', type:'spot', start:-970, title:'솔로몬 즉위',
    y: 11, heightPx: 30, z: 1, labelAlign:'right',
    description: '[왕상 1:28~53]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev031', lane:'biblical', type:'span', start:-966, end:-959, title:'예루살렘 성전 건축',
    y: 37, heightPx: 30, z: 1, labelAlign:'right',
    description: '[왕상 6:1, 8:14~20]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev032', lane:'biblical', type:'spot', start:-931, title:'이스라엘의 분열, 르호보암과 여로보암',
    y: 12, heightPx: 30, z: 1, labelAlign:'right',
    description: '[왕상 12:17, 20]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev033', lane:'biblical', type:'span', start:-931, end:-586, title:'분열 왕국 시대',
    y: 47, heightPx: 30, z: 1, labelAlign:'right',
    description: '[왕상 12장~왕하 25장, 대하 10장~36장]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev034', lane:'biblical', type:'spot', start:-722, title:'북이스라엘, 신아시리아에게 멸망',
    y: 44, heightPx: 30, z: 1, labelAlign:'right',
    description: '[왕하 17:6]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev035', lane:'biblical', type:'spot', start:-605, title:'1차 바벨론 유수',
    y: 90, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev036', lane:'biblical', type:'spot', start:-597, title:'2차 바벨론 유수',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev037', lane:'biblical', type:'spot', start:-586, title:'남유다 멸망, 3차 바벨론 유수',
    y: 45, heightPx: 30, z: 1, labelAlign:'right',
    description: '[대하 36:11~21]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev038', lane:'biblical', type:'span', start:-539, end:-538, title:'페르시아 키루스 2세 칙령, 1차 유대인 귀환',
    y: 23, heightPx: 30, z: 1, labelAlign:'right',
    description: '[스 1:1~4]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev039', lane:'biblical', type:'spot', start:-516, title:'성전 재건 완공',
    y: 42, heightPx: 30, z: 1, labelAlign:'right',
    description: '[스 3~6장, 느 3~7장]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev040', lane:'biblical', type:'spot', start:-479, title:'에스더, 페르시아 왕후 즉위',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '[에 2:17]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev041', lane:'biblical', type:'spot', start:-473, title:'페르시아 때 멸족 위기 모면',
    y: 64, heightPx: 30, z: 1, labelAlign:'right',
    description: '[에 3~8장]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev042', lane:'biblical', type:'spot', start:-458, title:'2차 유대인 귀환 [에스라]',
    y: 76, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev043', lane:'biblical', type:'spot', start:-444, title:'3차 유대인 귀환 [느헤미야]',
    y: 34, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev044', lane:'biblical', type:'spot', start:-420, title:'말라기서',
    y: 39, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev045', lane:'biblical', type:'span', start:-1050, end:-930, title:'왕정 시대',
    y: 43, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev046', lane:'biblical', type:'span', start:-5, end:30, title:'예수 그리스도',
    y: 63, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev047', lane:'biblical', type:'spot', start:30, title:'예수의 죽음과 부활',
    y: 21, heightPx: 30, z: 1, labelAlign:'right',
    description: '[요 19~21장]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev048', lane:'biblical', type:'spot', start:30, title:'오순절',
    y: 53, heightPx: 30, z: 1, labelAlign:'right',
    description: '[행 2:1~4]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev049', lane:'biblical', type:'spot', start:30, title:'교회 시대',
    y: 64, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev050', lane:'biblical', type:'span', start:30, end:100, title:'사도 시대',
    y: 42, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev051', lane:'biblical', type:'span', start:45, end:62, title:'바울의 선교 활동',
    y: 16, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev052', lane:'biblical', type:'spot', start:37, title:'가이사랴 이방인 최초 회심',
    y: 29, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev053', lane:'biblical', type:'spot', start:70, title:'예루살렘 성전 파괴',
    y: 15, heightPx: 30, z: 1, labelAlign:'right',
    description: '[마 24:1~2]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev054', lane:'biblical', type:'spot', start:1948, title:'이스라엘 독립',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '[겔 28:25]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev055', lane:'biblical', type:'spot', start:1991, title:'유대 민족의 대귀환',
    y: 80, heightPx: 30, z: 1, labelAlign:'right',
    description: '[사 43:6]',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev056', lane:'jewish', type:'span', start:-37, end:-4, title:'헤로데 대왕',
    y: 13, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev057', lane:'jewish', type:'spot', start:-22, title:'헤로데의 성전 증축',
    y: 16, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev058', lane:'jewish', type:'span', start:-4, end:39, title:'헤로데 안티파스 분봉왕',
    y: 82, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev059', lane:'jewish', type:'span', start:37, end:44, title:'헤로데 아그리파 1세',
    y: 38, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev060', lane:'jewish', type:'span', start:44, end:93, title:'헤로데 아그리파 2세',
    y: 89, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev061', lane:'jewish', type:'span', start:71, end:73, title:'마사다 항쟁',
    y: 58, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev062', lane:'jewish', type:'span', start:132, end:135, title:'바코흐바의 반란',
    y: 15, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev063', lane:'jewish', type:'spot', start:135, title:'예루살렘 출입 금지령, 방랑 생활의 시작',
    y: 44, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev064', lane:'jewish', type:'spot', start:380, title:'팔레스타인 탈무드 편집',
    y: 31, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev065', lane:'jewish', type:'spot', start:415, title:'알렉산드리아의 유대인 추방',
    y: 60, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev066', lane:'jewish', type:'spot', start:499, title:'바빌로니아 탈무드 편집',
    y: 45, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev067', lane:'jewish', type:'spot', start:638, title:'이슬람교, 예루살렘 점령',
    y: 27, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev068', lane:'jewish', type:'span', start:746, end:1016, title:'카자르국, 유대교 국교화',
    y: 86, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev069', lane:'jewish', type:'span', start:900, end:1000, title:'유대인 무역상들의 활약',
    y: 13, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev070', lane:'jewish', type:'spot', start:930, title:'히브리 성경, 권위본 확립',
    y: 45, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev071', lane:'jewish', type:'spot', start:1066, title:'그라나다 유대인 대학살',
    y: 51, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev072', lane:'jewish', type:'spot', start:1182, title:'프랑스의 유대인 추방',
    y: 44, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev073', lane:'jewish', type:'span', start:1200, end:1600, title:'유대인 강제 격리 구역 형성 활발',
    y: 54, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev074', lane:'jewish', type:'spot', start:1492, title:'스페인의 유대인 추방',
    y: 37, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev075', lane:'jewish', type:'spot', start:1516, title:'베네치아의 최초 게토 형성',
    y: 86, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev076', lane:'jewish', type:'span', start:1632, end:1677, title:'바룩 스피노자',
    y: 17, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev077', lane:'jewish', type:'spot', start:1654, title:'미국의 유대인 공동체 시작',
    y: 49, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev078', lane:'jewish', type:'spot', start:1744, title:'로스차일드 가문',
    y: 19, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev079', lane:'jewish', type:'span', start:1600, end:1800, title:'암스테르담 유대인 무역상들 활약',
    y: 26, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev080', lane:'jewish', type:'span', start:1500, end:1700, title:'유대인들의 아메리카 이주',
    y: 65, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev081', lane:'jewish', type:'span', start:1818, end:1883, title:'칼 마르크스',
    y: 13, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev082', lane:'jewish', type:'spot', start:1894, title:'드레퓌스 사건',
    y: 61, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev083', lane:'jewish', type:'spot', start:1897, title:'제 1차 시오니스트 회의, 스위스 바젤',
    y: 36, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev084', lane:'jewish', type:'span', start:1897, end:1955, title:'알버트 아인슈타인',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev085', lane:'jewish', type:'spot', start:1917, title:'밸푸어 선언, 유대인 국가 건립 약속',
    y: 46, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev086', lane:'jewish', type:'span', start:1938, end:1945, title:'홀로코스트',
    y: 78, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev087', lane:'jewish', type:'spot', start:1953, title:'AIPAC 설립',
    y: 38, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev088', lane:'jewish', type:'spot', start:-198, title:'셀레우코스가 이스라엘 지배',
    y: 19, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev089', lane:'jewish', type:'span', start:-175, end:-164, title:'안티오쿠스 4세',
    y: 58, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev090', lane:'jewish', type:'spot', start:-165, title:'마카비 항쟁 시작',
    y: 67, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev091', lane:'jewish', type:'spot', start:-150, title:'헬레니즘 사두개파와 율법주의 바리새파 분파',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev092', lane:'jewish', type:'span', start:-142, end:-63, title:'이스라엘 독립, 하스모니아 왕조 개창',
    y: 76, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev093', lane:'jewish', type:'spot', start:-63, title:'로마의 지배 시작',
    y: 47, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev094', lane:'jewish', type:'spot', start:1967, title:'제 3차 중동전쟁과 동예루살렘 탈환',
    y: 14, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev095', lane:'jewish', type:'spot', start:1973, title:'제 4차 중동전쟁, 석유 파동',
    y: 90, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev096', lane:'jewish', type:'spot', start:1993, title:'오슬로 이스라엘과 아랍 평화 협정',
    y: 60, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev097', lane:'church', type:'span', start:64, end:313, title:'교회 박해 시대',
    y: 27, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev098', lane:'church', type:'span', start:171, end:173, title:'하드리아누스 박해',
    y: 67, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev099', lane:'church', type:'spot', start:300, title:'그레고리우스, 아르메니아 대회심',
    y: 55, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev100', lane:'church', type:'spot', start:303, title:'디오클레티아누스의 대박해',
    y: 51, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev101', lane:'church', type:'spot', start:313, title:'밀라노 칙령, 로마에서 기독교 공인',
    y: 74, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev102', lane:'church', type:'spot', start:324, title:'유세비우스, 최초 교회사 정리',
    y: 89, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev103', lane:'church', type:'spot', start:325, title:'니케아 종교 회의, 예수의 신성 정립',
    y: 77, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev104', lane:'church', type:'spot', start:367, title:'아타나시우스, 신약 정리',
    y: 25, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev105', lane:'church', type:'spot', start:387, title:'로마 아우구스티누스의 회심',
    y: 73, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev106', lane:'church', type:'spot', start:392, title:'로마의 기독교 국교화',
    y: 66, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev107', lane:'church', type:'spot', start:405, title:'제롬의 라틴어 성경 번역',
    y: 18, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev108', lane:'church', type:'spot', start:440, title:'첫 교황 레오 1세 즉위',
    y: 30, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev109', lane:'church', type:'spot', start:451, title:'칼게돈 공의회',
    y: 49, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev110', lane:'church', type:'spot', start:498, title:'프랑크 클로비스 침례',
    y: 46, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev111', lane:'church', type:'spot', start:553, title:'2차 콘스탄티노플 회의, 성탄일 계산',
    y: 72, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev112', lane:'church', type:'spot', start:590, title:'그레고리우스 1세 교황 취임',
    y: 41, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev113', lane:'church', type:'span', start:590, end:1517, title:'교황 지상권 시대',
    y: 34, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev114', lane:'church', type:'spot', start:732, title:'투르 전투, 기독교와 이슬람교의 마찰',
    y: 17, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev115', lane:'church', type:'spot', start:800, title:'샤를마뉴 대제의 서로마 황제 대관',
    y: 68, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev116', lane:'church', type:'spot', start:962, title:'오토 1세, 신성 로마 제국 황제 대관',
    y: 47, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev117', lane:'church', type:'spot', start:1054, title:'동방 교회와 서방 교회의 분리',
    y: 39, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev118', lane:'church', type:'spot', start:1073, title:'힐데브란트 교황 등극',
    y: 27, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev119', lane:'church', type:'spot', start:1077, title:'카노사의 굴욕',
    y: 44, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev120', lane:'church', type:'span', start:1096, end:1270, title:'십자군 전쟁',
    y: 69, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev121', lane:'church', type:'spot', start:1170, title:'발덴스파의 복음 전파',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev122', lane:'church', type:'span', start:1309, end:1377, title:'교황의 아비뇽 유수',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev123', lane:'church', type:'span', start:1370, end:1415, title:'존 후스, 성경 중심 주의',
    y: 37, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev124', lane:'church', type:'span', start:1380, end:1382, title:'위클리프 성경',
    y: 74, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev125', lane:'church', type:'spot', start:1455, title:'구텐베르크 성경 인쇄',
    y: 31, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev126', lane:'church', type:'spot', start:1512, title:'루터의 회심',
    y: 37, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev127', lane:'church', type:'spot', start:1517, title:'루터의 95개조 반박문, 종교 개혁의 시작',
    y: 28, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev128', lane:'church', type:'spot', start:1523, title:'취리히 회의, 츠빙글리와 재침례파',
    y: 89, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev129', lane:'church', type:'spot', start:1529, title:'마르부르크, 성찬식 논쟁',
    y: 25, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev130', lane:'church', type:'spot', start:1533, title:'칼뱅의 회심',
    y: 68, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev131', lane:'church', type:'spot', start:1611, title:'킹제임스 성경 출판',
    y: 33, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev132', lane:'church', type:'spot', start:1620, title:'메이플라워호, 영국의 청교도가 미국으로 건너감',
    y: 54, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev133', lane:'church', type:'spot', start:1720, title:'진젠돌프 백작과 모라비아 형제단',
    y: 53, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev134', lane:'church', type:'span', start:1720, end:1750, title:'대각성 운동',
    y: 22, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev135', lane:'church', type:'spot', start:1738, title:'요한 웨슬레 회심',
    y: 21, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev136', lane:'church', type:'span', start:1830, end:1930, title:'전천년주의 주장',
    y: 72, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev137', lane:'church', type:'spot', start:1876, title:'한국에 최초로 개신교가 들어옴, 서상륜 등에게 전도',
    y: 64, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev138', lane:'church', type:'spot', start:1938, title:'성경 개역 간행',
    y: 76, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev139', lane:'church', type:'spot', start:1961, title:'성경전서 개역 한글판 간행',
    y: 53, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev140', lane:'church', type:'spot', start:1900, title:'대부흥 운동',
    y: 72, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev141', lane:'world', type:'spot', start:-3300, title:'메소포타미아 문명',
    y: 24, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev142', lane:'world', type:'spot', start:-3300, title:'수메르 문명',
    y: 27, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev143', lane:'world', type:'spot', start:-3100, title:'이집트 문명',
    y: 31, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev144', lane:'world', type:'spot', start:-3000, title:'초기 왕조 시대',
    y: 87, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev145', lane:'world', type:'spot', start:-2686, title:'고왕국 시대',
    y: 72, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev146', lane:'world', type:'span', start:-2589, end:-2566, title:'쿠푸 재위, 기자에 대피라미드 건설',
    y: 29, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev147', lane:'world', type:'spot', start:-2500, title:'우르 제 1왕조',
    y: 46, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev148', lane:'world', type:'spot', start:-2350, title:'아카드 왕조 사르곤 1세',
    y: 71, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev149', lane:'world', type:'spot', start:-2500, title:'인더스, 황하 문명 시작',
    y: 86, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev150', lane:'world', type:'spot', start:-2181, title:'제 1 중간기',
    y: 38, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev151', lane:'world', type:'spot', start:-2100, title:'수메르 부흥기 / 우르 제 3 왕조',
    y: 21, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev152', lane:'world', type:'spot', start:-2020, title:'이신-라르사 왕조',
    y: 69, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev153', lane:'world', type:'spot', start:-2055, title:'중왕국 시대',
    y: 45, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev154', lane:'world', type:'spot', start:-1850, title:'바빌로니아 제 1 왕조',
    y: 74, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev155', lane:'world', type:'span', start:-1792, end:-1750, title:'함무라비 : 바빌로니아 제 1 왕조 6대왕',
    y: 41, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev156', lane:'world', type:'spot', start:-1650, title:'제 2 중간기',
    y: 10, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev157', lane:'world', type:'spot', start:-1570, title:'바빌로니아 제 2왕조 [카시테 왕조]',
    y: 89, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev158', lane:'world', type:'spot', start:-1550, title:'신왕국 시대',
    y: 19, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev159', lane:'world', type:'spot', start:-1100, title:'메소포타미아 지역의 혼란기, 이스라엘의 부흥',
    y: 68, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev160', lane:'world', type:'span', start:-1279, end:-1213, title:'람세스 2세',
    y: 12, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev161', lane:'world', type:'spot', start:-1069, title:'제 3 중간기',
    y: 19, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev162', lane:'world', type:'spot', start:-911, title:'신아시리아 성장기',
    y: 79, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev163', lane:'world', type:'span', start:-745, end:-609, title:'신아시리아 제국',
    y: 14, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev164', lane:'world', type:'span', start:-700, end:-340, title:'말기 왕조 시대',
    y: 25, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev165', lane:'world', type:'span', start:-605, end:-539, title:'신바빌로니아 제국',
    y: 19, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev166', lane:'world', type:'span', start:-563, end:-483, title:'석가모니',
    y: 14, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev167', lane:'world', type:'span', start:-551, end:-479, title:'공자',
    y: 54, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev168', lane:'world', type:'spot', start:-539, title:'페르시아 키루스 2세가 바벨론 점령',
    y: 26, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev169', lane:'world', type:'span', start:-559, end:-330, title:'페르시아 제국',
    y: 34, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev170', lane:'world', type:'spot', start:-480, title:'살라미스 해전에서 그리스에게 패배',
    y: 40, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev171', lane:'world', type:'span', start:-334, end:-323, title:'알렉산드로스 대왕의 동방 원정과 헬라 제국 건립',
    y: 27, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev172', lane:'world', type:'span', start:-323, end:-30, title:'헬레니즘 시대',
    y: 51, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev173', lane:'world', type:'spot', start:-323, title:'헬라 분열 후 프톨레마이우스가 이스라엘 지배',
    y: 35, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev174', lane:'world', type:'span', start:-305, end:-148, title:'마케도니아',
    y: 53, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev175', lane:'world', type:'span', start:-312, end:-64, title:'셀레우코스 왕국',
    y: 83, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev176', lane:'world', type:'span', start:-305, end:-30, title:'프톨레마이우스 왕국',
    y: 55, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev177', lane:'world', type:'spot', start:-146, title:'포에니 전쟁에서 로마 최종 승리',
    y: 32, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev178', lane:'world', type:'spot', start:-45, title:'로마, 카이사르의 독재',
    y: 18, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev179', lane:'world', type:'span', start:-27, end:476, title:'로마 제국',
    y: 59, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev180', lane:'world', type:'spot', start:-27, title:'로마 아우구스투스, 황제 즉위',
    y: 34, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev181', lane:'world', type:'span', start:14, end:37, title:'티베리우스',
    y: 39, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev182', lane:'world', type:'span', start:26, end:36, title:'본디오 빌라도 유대 총독',
    y: 59, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev183', lane:'world', type:'span', start:37, end:41, title:'칼리굴라',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev184', lane:'world', type:'span', start:41, end:54, title:'클라우디우스',
    y: 83, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev185', lane:'world', type:'span', start:52, end:58, title:'벨릭스 유대 총독',
    y: 62, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev186', lane:'world', type:'span', start:54, end:68, title:'네로',
    y: 82, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev187', lane:'world', type:'span', start:58, end:62, title:'베스도 유대 총독',
    y: 22, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev188', lane:'world', type:'spot', start:395, title:'로마 분열, 서로마와 동로마',
    y: 89, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev189', lane:'world', type:'spot', start:476, title:'서로마 제국 멸망',
    y: 57, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev190', lane:'world', type:'span', start:570, end:632, title:'무함마드',
    y: 59, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev191', lane:'world', type:'spot', start:610, title:'이슬람교 창시',
    y: 47, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev192', lane:'world', type:'spot', start:711, title:'무슬림이 스페인 점령',
    y: 31, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev193', lane:'world', type:'span', start:1040, end:1194, title:'셀주크 튀르크',
    y: 23, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev194', lane:'world', type:'spot', start:1071, title:'만지케르트 전투에서 비잔티움 제국을 이김',
    y: 80, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev195', lane:'world', type:'spot', start:1095, title:'비잔티움 제국, 뺏긴 예루살렘 탈환 종용',
    y: 51, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev196', lane:'world', type:'span', start:1300, end:1500, title:'유럽에 흑사병 대유행',
    y: 70, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev197', lane:'world', type:'span', start:1300, end:1600, title:'유럽의 르네상스',
    y: 60, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev198', lane:'world', type:'spot', start:1450, title:'구텐베르크, 활판 인쇄기 발명',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev199', lane:'world', type:'spot', start:1453, title:'비잔티움 제국 멸망',
    y: 39, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev200', lane:'world', type:'spot', start:1492, title:'콜럼버스, 신대륙 발견',
    y: 47, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev201', lane:'world', type:'spot', start:1543, title:'코페르니쿠스, 지동설 발표',
    y: 22, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev202', lane:'world', type:'spot', start:1687, title:'뉴턴, 만유 인력의 법칙 발표',
    y: 26, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev203', lane:'world', type:'spot', start:1764, title:'와트의 증기 기관 개량',
    y: 34, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev204', lane:'world', type:'spot', start:1789, title:'프랑스 혁명',
    y: 43, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev205', lane:'world', type:'spot', start:1859, title:'다윈, 종의 기원 출간',
    y: 56, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev206', lane:'world', type:'span', start:1914, end:1918, title:'제 1차 세계대전',
    y: 31, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev207', lane:'world', type:'spot', start:1929, title:'세계 경제 대공황',
    y: 83, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev208', lane:'world', type:'span', start:1939, end:1945, title:'제 2차 세계대전',
    y: 50, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev209', lane:'world', type:'spot', start:1945, title:'UN 탄생',
    y: 66, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev210', lane:'world', type:'spot', start:1963, title:'핵 실험 금지 협정',
    y: 34, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev211', lane:'world', type:'spot', start:1964, title:'팔레스타인 해방기구(PLO) 창설',
    y: 58, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev212', lane:'world', type:'spot', start:1969, title:'미국 아폴로 11호 달 착륙',
    y: 20, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev213', lane:'world', type:'spot', start:1991, title:'소련 해체',
    y: 74, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev214', lane:'world', type:'spot', start:2001, title:'9·11 테러',
    y: 73, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'ev215', lane:'world', type:'spot', start:2004, title:'유럽 연합[EU] 25개국 확대',
    y: 36, heightPx: 30, z: 1, labelAlign:'right',
    description: '',
    zoomVisibility:[true,true,true,true,true] }
];

export const CONNECTIONS_INITIAL = [
  { from:'ev103', to:'ev104' }, // 로마 제국 -> 교회 박해 시대 (approximate)
];

export const RANGE = { min: -4500, max: 2500 };

export const ZOOM_LEVELS = [
  { id: 1, scale: 0.18,  label: '전체',   majorStep: 1000, minorStep: 200 },
  { id: 2, scale: 0.55,  label: '시대',   majorStep: 200,  minorStep: 50  },
  { id: 3, scale: 1.6,   label: '세기',   majorStep: 100,  minorStep: 20  },
  { id: 4, scale: 4.5,   label: '10년',   majorStep: 50,   minorStep: 10  },
  { id: 5, scale: 12,    label: '연도',   majorStep: 10,   minorStep: 1   },
];

export const LANE_H = 110;
export const TOTAL_H = LANE_H * LANES.length; // 440

export const PAD_LEFT = 180;
export const PAD_RIGHT = 300;
