/* ============================================================
   성경 세계사 연대표 — Data (ES module)
   Converted from window.* globals in design_handoff_timetable/data.js
   ============================================================ */

export const LANES = [
  { id: 'world',    label: '세계 역사',  watermark: 'WORLD HISTORY',     theme: 'light' },
  { id: 'church',   label: '교회 역사',  watermark: 'CHURCH HISTORY',    theme: 'dark', skew: true },
  { id: 'jewish',   label: '유대 역사',  watermark: 'JEWISH HISTORY',    theme: 'light' },
  { id: 'biblical', label: '성경 연대',  watermark: 'BIBLICAL TIMELINE', theme: 'dark', skew: true },
];

export const EVENTS_INITIAL = [
  // ============ WORLD ============
  { id: 'meso',  lane:'world', type:'span', start:-3500, end:-539, title:'메소포타미아 문명',
    y: 8,  heightPx: 92, fill: 0.20, z: 1, labelAlign:'right',
    description: '티그리스·유프라테스 강 유역에서 일어난 인류 최초의 문명. 수메르, 아카드, 바빌로니아, 앗시리아 등이 포함된다.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'egypt', lane:'world', type:'span', start:-3100, end:-30, title:'고대 이집트',
    y: 8,  heightPx: 92, fill: 0.30, z: 2, labelAlign:'right',
    description: '나일강 하류에서 약 3000년간 지속된 고대 문명. 클레오파트라 7세 사후 로마에 병합되었다.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'indus', lane:'world', type:'span', start:-2600, end:-1900, title:'인더스 문명',
    y: 16, heightPx: 28, fill: 0.40, z: 4, labelAlign:'right', labelOutside:true,
    description: '오늘날 파키스탄·인도 북서부 인더스강 유역의 청동기 문명.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'shang', lane:'world', type:'span', start:-1600, end:-1046, title:'중국 상나라',
    y: 50, heightPx: 28, fill: 0.40, z: 4, labelAlign:'right',
    description: '갑골문이 발견된 중국 최초의 확실한 왕조.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'persia',lane:'world', type:'span', start:-550, end:-330, title:'페르시아 제국',
    y: 16, heightPx: 30, fill: 0.45, z: 4, labelAlign:'right',
    description: '아케메네스 왕조. 키루스 2세가 바빌론을 정복하고 유다 포로를 귀환시켰다.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'helle', lane:'world', type:'span', start:-323, end:-30, title:'헬레니즘',
    y: 52, heightPx: 28, fill: 0.40, z: 4, labelAlign:'right',
    description: '알렉산더 대왕 사후부터 로마의 이집트 정복까지의 시기.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'rome',  lane:'world', type:'span', start:-27, end:476, title:'로마 제국',
    y: 4, heightPx: 100, fill: 0.55, z: 3, labelAlign:'right',
    description: '아우구스투스의 즉위로 시작되어 서로마 멸망까지 약 500년간 지속된 제국.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'byzant',lane:'world', type:'span', start:330, end:1453, title:'비잔틴 제국',
    y: 4, heightPx: 36, fill: 0.40, z: 3, labelAlign:'right',
    description: '동로마 제국. 콘스탄티노플 함락으로 종결되었다.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'tang',  lane:'world', type:'span', start:618, end:907, title:'당',
    y: 44, heightPx: 28, fill: 0.40, z: 4, labelAlign:'right',
    description: '중국의 통일 왕조 중 하나. 동서 교류의 전성기.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'mongol',lane:'world', type:'span', start:1206, end:1368, title:'몽골 제국',
    y: 76, heightPx: 24, fill: 0.45, z: 5, labelAlign:'right', labelOutside:true,
    description: '칭기즈 칸이 세운 사상 최대 영토의 유목 제국.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'choson',lane:'world', type:'span', start:1392, end:1897, title:'조선',
    y: 44, heightPx: 28, fill: 0.40, z: 4, labelAlign:'right',
    description: '이성계가 건국한 한반도의 마지막 왕조.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'ww1',   lane:'world', type:'spot', start:1914, title:'1차 세계대전', y: 30, heightPx: 40,
    labelAlign:'right', description: '1914-1918. 사라예보 사건으로 촉발.',
    zoomVisibility:[false,false,false,true,true] },
  { id: 'ww2',   lane:'world', type:'spot', start:1939, title:'2차 세계대전', y: 30, heightPx: 40,
    labelAlign:'right', description: '1939-1945. 인류 최대의 무력 충돌.',
    zoomVisibility:[false,false,false,true,true] },

  // ============ CHURCH (lane 1: y 110~220) ============
  { id: 'pentecost', lane:'church', type:'spot', start:30, title:'오순절 성령강림', y: 128, heightPx: 78,
    labelAlign:'right', description: '예수 부활 후 50일째 성령이 강림한 사건. 교회의 시작으로 본다.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'milan',   lane:'church', type:'spot', start:313, title:'밀라노 칙령', y: 128, heightPx: 78,
    labelAlign:'right', description: '콘스탄티누스가 기독교를 합법화한 칙령.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'nicaea',  lane:'church', type:'spot', start:325, title:'니케아 공의회', y: 128, heightPx: 78,
    labelAlign:'left', description: '삼위일체 교리를 정립한 최초의 보편 공의회.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'pope',    lane:'church', type:'span', start:590, end:1303, title:'교황 지상권 시대',
    y: 122, heightPx: 86, fill: 0.30, z: 2, labelAlign:'right',
    description: '그레고리오 1세부터 보니파시오 8세까지 교황권이 세속 권력보다 우위에 있던 시기.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'eastsplit',lane:'church', type:'spot', start:1054, title:'동서 교회 분열', y: 128, heightPx: 78,
    labelAlign:'right', description: '로마 가톨릭과 동방 정교회의 공식 분열.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'crusade', lane:'church', type:'span', start:1095, end:1291, title:'십자군',
    y: 114, heightPx: 24, fill: 0.45, z: 4, labelAlign:'right', labelOutside:true,
    description: '성지 회복을 명분으로 한 8차에 걸친 원정.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'luther',  lane:'church', type:'spot', start:1517, title:'루터 95개조', y: 118, heightPx: 88,
    labelAlign:'right', description: '마르틴 루터의 95개조 반박문 게시. 종교개혁의 시작.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'westphalia', lane:'church', type:'spot', start:1648, title:'베스트팔렌 조약', y: 118, heightPx: 88,
    labelAlign:'left', description: '30년 전쟁을 종결한 조약. 종교 자유의 기반.',
    zoomVisibility:[false,false,false,true,true] },
  { id: 'vatican2', lane:'church', type:'spot', start:1962, title:'제2차 바티칸', y: 128, heightPx: 78,
    labelAlign:'left', description: '교회의 현대화를 추진한 가톨릭 공의회.',
    zoomVisibility:[false,false,false,true,true] },

  // ============ JEWISH (lane 2: y 220~330) ============
  { id: 'unitedmon', lane:'jewish', type:'span', start:-1050, end:-931, title:'통일 왕국',
    y: 258, heightPx: 30, fill: 0.45, z: 4, labelAlign:'right',
    description: '사울·다윗·솔로몬으로 이어진 이스라엘 통일 왕국 시대.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'split',   lane:'jewish', type:'spot', start:-931, title:'이스라엘 분열', y: 238, heightPx: 78,
    labelAlign:'right', description: '솔로몬 사후 북이스라엘과 남유다로 분열.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'assyria', lane:'jewish', type:'spot', start:-722, title:'북이스라엘 멸망', y: 238, heightPx: 78,
    labelAlign:'left', description: '앗시리아의 사르곤 2세에 의해 사마리아 함락.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'exile',   lane:'jewish', type:'span', start:-605, end:-539, title:'바벨론 유수',
    y: 238, heightPx: 32, fill: 0.45, z: 5, labelAlign:'right', labelOutside:true,
    description: '바빌로니아 제국에 의한 유다인 강제 이주.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'return',  lane:'jewish', type:'spot', start:-538, title:'귀환', y: 270, heightPx: 40,
    labelAlign:'right', description: '키루스 칙령에 의한 1차 귀환.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'temple2', lane:'jewish', type:'spot', start:-516, title:'제2성전 완성', y: 270, heightPx: 40,
    labelAlign:'left', description: '스룹바벨이 주도하여 재건한 예루살렘 성전.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'macca',   lane:'jewish', type:'span', start:-167, end:-37, title:'마카비/하스몬',
    y: 280, heightPx: 28, fill: 0.40, z: 5, labelAlign:'right', labelOutside:true,
    description: '마카비 항쟁으로 시작된 유대 독립 왕조.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'ad70',    lane:'jewish', type:'spot', start:70, title:'예루살렘 멸망', y: 238, heightPx: 78,
    labelAlign:'right', description: '로마 티투스에 의한 제2성전 파괴.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'masada',  lane:'jewish', type:'span', start:71, end:73, title:'마사다 항쟁',
    y: 232, heightPx: 22, fill: 0.45, z: 5, labelAlign:'right', labelOutside:true,
    description: '마사다 요새에서 벌어진 유대인 최후의 저항.',
    zoomVisibility:[false,false,false,true,true] },
  { id: 'diaspora',lane:'jewish', type:'span', start:135, end:1948, title:'디아스포라',
    y: 270, heightPx: 28, fill: 0.20, z: 1, labelAlign:'right',
    description: '바르 코크바 반란 진압 후 유대인의 세계 흩어짐.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'israel',  lane:'jewish', type:'spot', start:1948, title:'이스라엘 독립', y: 238, heightPx: 78,
    labelAlign:'left', description: '1948년 5월 14일, 현대 이스라엘 국가 수립.',
    zoomVisibility:[false,true,true,true,true] },

  // ============ BIBLICAL (lane 3: y 330~440) ============
  { id: 'adam',    lane:'biblical', type:'spot', start:-4200, title:'아담과 하와', y: 344, heightPx: 82,
    labelAlign:'right', description: '창세기에 기록된 인류의 시작.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'noah',    lane:'biblical', type:'spot', start:-2400, title:'노아 홍수', y: 344, heightPx: 82,
    labelAlign:'right', description: '창세기 6-9장의 대홍수 사건.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'abraham', lane:'biblical', type:'spot', start:-2000, title:'아브라함', y: 344, heightPx: 82,
    labelAlign:'right', description: '믿음의 조상. 가나안으로의 부르심.',
    zoomVisibility:[false,true,true,true,true] },
  { id: 'exodus',  lane:'biblical', type:'spot', start:-1446, title:'출애굽', y: 344, heightPx: 82,
    labelAlign:'right', description: '모세의 인도 하에 이스라엘이 이집트를 떠난 사건.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'david',   lane:'biblical', type:'spot', start:-1010, title:'다윗 왕', y: 344, heightPx: 82,
    labelAlign:'left', description: '이스라엘 통일왕국의 두 번째 왕.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'jesus',   lane:'biblical', type:'span', start:-5, end:30, title:'예수 그리스도',
    y: 338, heightPx: 92, fill: 0.65, z: 5, labelAlign:'right',
    description: '예수의 탄생부터 십자가·부활까지의 공생애.',
    zoomVisibility:[true,true,true,true,true] },
  { id: 'paul',    lane:'biblical', type:'span', start:46, end:67, title:'바울 전도여행',
    y: 390, heightPx: 28, fill: 0.45, z: 5, labelAlign:'right', labelOutside:true,
    description: '바울의 1·2·3차 선교여행과 로마 압송까지의 시기.',
    zoomVisibility:[false,false,true,true,true] },
  { id: 'rev',     lane:'biblical', type:'spot', start:95, title:'요한계시록', y: 360, heightPx: 50,
    labelAlign:'left', description: '사도 요한이 밧모섬에서 받은 묵시.',
    zoomVisibility:[false,false,false,true,true] },
];

export const CONNECTIONS_INITIAL = [
  { from:'rome', to:'pope' },
  { from:'rome', to:'jesus' },
  { from:'exile', to:'return' },
];

export const RANGE = { min: -4500, max: 2500 };

export const ZOOM_LEVELS = [
  { id: 1, scale: 0.18,  label: '전체',   majorStep: 1000, minorStep: 200 },
  { id: 2, scale: 0.55,  label: '시대',   majorStep: 200,  minorStep: 50  },
  { id: 3, scale: 1.6,   label: '세기',   majorStep: 100,  minorStep: 20  },
  { id: 4, scale: 4.5,   label: '10년',   majorStep: 50,   minorStep: 10  },
  { id: 5, scale: 12,    label: '연도',   majorStep: 10,   minorStep: 1   },
];

export const LANE_H = 110;
export const TOTAL_H = LANE_H * LANES.length; // 440

export const PAD_LEFT = 180;
export const PAD_RIGHT = 300;
